#ifndef INCLUDE_UTIL_CONFIG_HPP
#define INCLUDE_UTIL_CONFIG_HPP

#if defined(BOOST_PP_VARIADICS)
# undef BOOST_PP_VARIADICS
#else
# define BOOST_PP_VARIADICS 1
#endif

#endif /* INCLUDE_UTIL_CONFIG_HPP */
